# Generated by Django 4.1 on 2022-08-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofadministrativeposition',
            name='type_position',
            field=models.CharField(help_text='приклад: Директор гімназії | Заступник директора з навчально-виховної роботи...', max_length=64, unique=True, verbose_name='посада'),
        ),
    ]
