# Generated by Django 4.1 on 2022-08-10 23:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_created', models.DateField(verbose_name='Дата публікації')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публікувати')),
            ],
            options={
                'verbose_name_plural': 'Новини',
            },
        ),
    ]
