# Generated by Django 4.1 on 2022-08-15 08:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
    ]
