# Generated by Django 4.1 on 2022-08-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_imageofpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageofpost',
            name='image',
            field=models.ImageField(upload_to='image_of_post/%Y/%m', verbose_name='зображення'),
        ),
    ]
