# Generated by Django 4.1 on 2022-08-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_imageofpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(help_text='пишіть кожне слово з великої літери', max_length=64, unique=True, verbose_name='назва'),
        ),
    ]
