# Generated by Django 4.1 on 2022-08-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(help_text='перше слово має бути з великої літери', max_length=64, unique=True, verbose_name='назва'),
        ),
    ]
