# Generated by Django 4.1 on 2022-08-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('class_name_icon', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
    ]
