# Generated by Django 4.1 on 2022-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_facility_delete_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name="ім'я")),
                ('profession', models.CharField(max_length=32, verbose_name='професія')),
                ('photo', models.ImageField(help_text='фото має бути розміром 100x100 px', upload_to='testimonials', verbose_name='фото')),
                ('text', models.CharField(max_length=256, verbose_name='відгук')),
            ],
            options={
                'verbose_name_plural': 'Відгуки',
            },
        ),
    ]
