# Generated by Django 4.1 on 2022-08-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='професія'),
        ),
    ]
