# Generated by Django 4.1 on 2022-08-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_facility_class_name_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_menu', models.CharField(choices=[('main_menu', 'головне меню'), ('footer_menu_row1', 'меню підвалу 1-ша колонка'), ('footer_menu_row2', 'меню підвалу 2-га колонка')], max_length=64, unique=True, verbose_name='тип меню')),
                ('json', models.JSONField(default={'data': [{'name': 'Головна'}, {'name': 'Новини'}]}, help_text='Для зручної роботи з JSON використовуйте JSONReader https://jsonformatter.org/')),
            ],
            options={
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
