# Generated by Django 4.1 on 2022-08-19 18:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_menu_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('style', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark')], max_length=32)),
                ('body', tinymce.models.HTMLField()),
                ('is_published', models.BooleanField(default=True, verbose_name='Публікувати')),
            ],
            options={
                'verbose_name_plural': 'Оголошення',
            },
        ),
    ]
