# Generated by Django 4.1 on 2022-08-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='mass',
            field=models.SmallIntegerField(default=0, help_text='позиція має бути унікальним для кожногї зручності', unique=True, verbose_name='позиція'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(help_text="дотримуйтесь заздалегіть вибраного шаблону. Приклад: прізвище, ім'я або ім'я та по батькові", max_length=32, verbose_name="ім'я"),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(blank=True, help_text='перше слово з маленької букви', max_length=32, null=True, verbose_name='професія'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.CharField(help_text='всі відгуки мають місти однакову кількість слів для кращого дизайну', max_length=256, verbose_name='відгук'),
        ),
    ]
