# Generated by Django 4.1 on 2022-08-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageofpage',
            name='name',
            field=models.CharField(default=0, max_length=64, unique=True, verbose_name='назава'),
            preserve_default=False,
        ),
    ]
