# Generated by Django 4.1 on 2022-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_imageofpage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageofpage',
            name='name',
            field=models.CharField(max_length=64, verbose_name='назава'),
        ),
    ]
