# Generated by Django 4.1 on 2022-08-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_imageofpage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='relative_link',
            field=models.SlugField(help_text='посилання не має містити лише латинські літери, цифри та символ ніжнього підкреслення, приклад: video_gallery', max_length=64, unique=True, verbose_name='відносне посилання'),
        ),
    ]
