# Generated by Django 4.1 on 2022-08-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='lessons',
            field=models.ManyToManyField(to='teachers.lesson'),
        ),
    ]
