# Generated by Django 4.1 on 2022-08-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_ranks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='ranks',
            field=models.ManyToManyField(blank=True, to='teachers.rank'),
        ),
    ]
