# Generated by Django 4.1 on 2022-08-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_ranks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name_plural': 'Звання'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.category', verbose_name='категорія'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lessons',
            field=models.ManyToManyField(to='teachers.lesson', verbose_name='уроки'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='ranks',
            field=models.ManyToManyField(blank=True, to='teachers.rank', verbose_name='звання'),
        ),
    ]
