# Generated by Django 4.1 on 2022-08-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_alter_teacher_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='genitive_case_of_name',
            field=models.CharField(default=0, help_text='приклад: математики', max_length=64, unique=True, verbose_name='родовий відмінок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(help_text='приклад: математика', max_length=64, unique=True, verbose_name='назва'),
        ),
    ]
