# Generated by Django 4.1 on 2022-08-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_lesson_genitive_case_of_name_alter_lesson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='genitive_case_of_name',
            field=models.CharField(help_text='приклад: математики', max_length=64, verbose_name='родовий відмінок'),
        ),
    ]
