# Generated by Django 4.1 on 2022-08-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_lesson_genitive_case_of_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='genitive_case_of_name',
            field=models.CharField(help_text='приклад: математики', max_length=64, unique=True, verbose_name='родовий відмінок'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachers.category', verbose_name='категорія'),
        ),
    ]
