# Generated by Django 4.1 on 2022-08-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_alter_lesson_genitive_case_of_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='teachers.lesson', verbose_name='уроки'),
        ),
    ]
