# Generated by Django 4.1 on 2022-08-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_alter_teacher_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mass',
            field=models.SmallIntegerField(default=0, help_text='ранг має бути унікальним для кожногї категорії', unique=True, verbose_name='ранг'),
        ),
    ]
