# Generated by Django 4.1 on 2022-08-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
