# Generated by Django 4.1 on 2022-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_alter_platform_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
