# Generated by Django 4.1 on 2022-08-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_typeofsocialnetwork_class_name_and_more'),
        ('certificate', '0003_certificate_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name_plural': 'Платформа'},
        ),
        migrations.AlterModelOptions(
            name='typedoc',
            options={'verbose_name_plural': 'Тип документу'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(verbose_name='Дата видачі'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='number_of_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Кількість годин'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.person', verbose_name='Працівник'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.platform', verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='type_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.typedoc', verbose_name='Тип документу'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='typedoc',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Назва'),
        ),
    ]
